/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import javax.swing.JInternalFrame;

/**
 *
 * @author rapha
 */
public class PrincipalV extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalV
     */
    public PrincipalV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        JDP = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        JMenu = new javax.swing.JMenu();
        JMCadastroDadosPessoais = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMCadastroDadosPessoais1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMCadastroDadosPessoais2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JDP.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout JDPLayout = new javax.swing.GroupLayout(JDP);
        JDP.setLayout(JDPLayout);
        JDPLayout.setHorizontalGroup(
            JDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        JDPLayout.setVerticalGroup(
            JDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        JMenu.setText("Empregado");

        JMCadastroDadosPessoais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        JMCadastroDadosPessoais.setText("Cadastro Empregado");
        JMCadastroDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastroDadosPessoaisActionPerformed(evt);
            }
        });
        JMenu.add(JMCadastroDadosPessoais);

        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenu.add(jMenuItem1);

        jMenuItem2.setText("Buscar");
        JMenu.add(jMenuItem2);

        jMenuItem3.setText("Remover");
        JMenu.add(jMenuItem3);

        jMenu.add(JMenu);

        jMenu2.setText("Vendedor");

        JMCadastroDadosPessoais1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        JMCadastroDadosPessoais1.setText("Cadastro Empregado");
        JMCadastroDadosPessoais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastroDadosPessoais1ActionPerformed(evt);
            }
        });
        jMenu2.add(JMCadastroDadosPessoais1);

        jMenuItem4.setText("Atualizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Buscar");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Remover");
        jMenu2.add(jMenuItem6);

        jMenuItem10.setText("Pontução");
        jMenu2.add(jMenuItem10);

        jMenu.add(jMenu2);

        jMenu1.setText("Gerente");

        JMCadastroDadosPessoais2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        JMCadastroDadosPessoais2.setText("Cadastro Empregado");
        JMCadastroDadosPessoais2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCadastroDadosPessoais2ActionPerformed(evt);
            }
        });
        jMenu1.add(JMCadastroDadosPessoais2);

        jMenuItem7.setText("Atualizar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Buscar");
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Remover");
        jMenu1.add(jMenuItem9);

        jMenu.add(jMenu1);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMCadastroDadosPessoais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastroDadosPessoais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMCadastroDadosPessoais1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void JMCadastroDadosPessoais2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCadastroDadosPessoais2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMCadastroDadosPessoais2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void JMCadastroDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {
        TelaCadastroEmpregadoV telaCadastro = new TelaCadastroEmpregadoV();
        telaCadastro.setLocation(
            (JDP.getWidth() - telaCadastro.getWidth()) / 2,
            (JDP.getHeight() - telaCadastro.getHeight()) / 2
        );
        JDP.add(telaCadastro);
        telaCadastro.setVisible(true);
        telaCadastro.toFront(); // Garante que a tela fique em primeiro plano
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDP;
    private javax.swing.JMenuItem JMCadastroDadosPessoais;
    private javax.swing.JMenuItem JMCadastroDadosPessoais1;
    private javax.swing.JMenuItem JMCadastroDadosPessoais2;
    private javax.swing.JMenu JMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
