/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import controle.GradeC;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rf5974
 */
public class GradeConsultaV extends javax.swing.JInternalFrame {
    GradeC gradec=new GradeC();
    ResultSet grade;
    DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form GradeConsultaV
     */
    public GradeConsultaV() {
        initComponents();
        // COnfigura o nome das colunas na JTable        
        modelo.addColumn("CURSO");
        modelo.addColumn("GRADE");
        modelo.addColumn("TOTAL DE SEMESTRES");
        modelo.addColumn("C.H. SEMESTRAL");
        //Adicionar a Configuração nas colunas da JTable
        JTBGrade.setModel(modelo);
        //Definindo o tamanho das colunas na Interface Gráfica
        JTBGrade.getColumnModel().getColumn(0).setPreferredWidth(160);
        JTBGrade.getColumnModel().getColumn(1).setPreferredWidth(35);
        JTBGrade.getColumnModel().getColumn(2).setPreferredWidth(80);
        JTBGrade.getColumnModel().getColumn(3).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTGrade = new javax.swing.JTextField();
        JBPorGrade = new javax.swing.JButton();
        JBTodas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JSPTabela = new javax.swing.JScrollPane();
        JTBGrade = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Grades:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Código da Grade:");

        JBPorGrade.setText("Por Grade");
        JBPorGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintPorCodGrade(evt);
            }
        });

        JBTodas.setText("Todas");
        JBTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintTodasAsGrades(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(JTGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(JBPorGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(JBTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPorGrade)
                    .addComponent(JBTodas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Impressão:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        JTBGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JSPTabela.setViewportView(JTBGrade);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSPTabela)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSPTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintTodasAsGrades(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintTodasAsGrades
                       
        try{
            grade=gradec.ContaGeralGrades();
            //contador de Linhas da JTable        
            int j=0;
            while(grade.next()){
                modelo.setNumRows(j+1);
                for(int i=1;i<=4;i++)
                {                
                    if(i==1){
                        JTBGrade.setValueAt(grade.getString(i),j,i-1);
                    }
                    else
                        JTBGrade.setValueAt(grade.getInt(i),j,i-1);
                }
                j++;
            }
        }catch(Exception er){
            er.printStackTrace();
        }
    }//GEN-LAST:event_PrintTodasAsGrades

    private void PrintPorCodGrade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintPorCodGrade
        try{
            int codgrade=Integer.parseInt(JTGrade.getText());
            
            grade=gradec.ContaGradesPorCOdGrade(codgrade);
            //contador de Linhas da JTable        
            int j=0;
            while(grade.next()){
                modelo.setNumRows(j+1);
                for(int i=1;i<=4;i++)
                {                
                    if(i==1){
                        JTBGrade.setValueAt(grade.getString(i),j,i-1);
                    }
                    else
                        JTB Grade.setValueAt(grade.getInt(i),j,i-1);
                }
                j++;
            }
        }catch(Exception er){
            er.printStackTrace();
        }
    }//GEN-LAST:event_PrintPorCodGrade


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBPorGrade;
    private javax.swing.JButton JBTodas;
    private javax.swing.JScrollPane JSPTabela;
    private javax.swing.JTable JTBGrade;
    private javax.swing.JTextField JTGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
