/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import javax.swing.JInternalFrame;

/**
 *
 * @author rf5974
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDPMain = new javax.swing.JDesktopPane();
        JMBPrincipal = new javax.swing.JMenuBar();
        JMCadastro = new javax.swing.JMenu();
        JMIGrade = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMHPrintGrade = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDPMainLayout = new javax.swing.GroupLayout(JDPMain);
        JDPMain.setLayout(JDPMainLayout);
        JDPMainLayout.setHorizontalGroup(
            JDPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        JDPMainLayout.setVerticalGroup(
            JDPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        JMCadastro.setText("Cadastro");

        JMIGrade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        JMIGrade.setText("Grade");
        JMIGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroGrade(evt);
            }
        });
        JMCadastro.add(JMIGrade);

        JMBPrincipal.add(JMCadastro);

        jMenu2.setText("Consulta");

        JMHPrintGrade.setText("Grade");
        JMHPrintGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintAllGrade(evt);
            }
        });
        jMenu2.add(JMHPrintGrade);

        JMBPrincipal.add(jMenu2);

        jMenu1.setText("Relatórios");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        JMBPrincipal.add(jMenu1);

        setJMenuBar(JMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDPMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDPMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroGrade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroGrade
        JInternalFrame CadastroGrade=new GradeCadastroV();
        CadastroGrade.pack();
        JDPMain.add(CadastroGrade);
        CadastroGrade.setVisible(true);
    }//GEN-LAST:event_CadastroGrade

    private void PrintAllGrade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintAllGrade
        JInternalFrame PrintGrade=new GradeConsultaV();
        PrintGrade.pack();
        JDPMain.add(PrintGrade);
        PrintGrade.setVisible(true);
    }//GEN-LAST:event_PrintAllGrade

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JInternalFrame Semestre = new GradeSemestreV();
        Semestre.pack();
        JDPMain.add(Semestre);
        Semestre.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPMain;
    private javax.swing.JMenuBar JMBPrincipal;
    private javax.swing.JMenu JMCadastro;
    private javax.swing.JMenuItem JMHPrintGrade;
    private javax.swing.JMenuItem JMIGrade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
